name: dev-YAML
environment: development
spring:
  security:
    user:
      name: user
      password: demo@123
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# Additional development-specific configurations can be added here
project:
  path:
    files:
      image: images/

  jwt:
    secret: mySecretKey123!#03584
    expiration-ms: 30000000000000

